### ISSUE TITLE
Shelly BLU Button1 on PlugSG3: out_of_memory error

### ISSUE THREAD

**Issue by alexwala** [ALLTERCO/shelly-script-examples#138]
**Describe the bug**
Getting 'out_of_memory' using ble-shelly-blu.js and ble-events-handler.js on PlugSG3 when clicking Shelly BLU Button1

**To Reproduce**
1. load ble-shelly-blu.js from library
2. load ble-events-handler.js from library
3. start both scripts
4. Click on Shelly BLU Button1
5. See error

**Expected behavior**
No 'out_of_memory' error

**Screenshots**
shelly_notification:163 Status change of script:2: {"id":2,"errors":["out_of_memory"],"running":false}

**Device and script details (please complete the following information):**
 - Firmware version 20240820-134301/1.2.3-plugsg3prod0-gec79607
 - Link to the script you were running [ble-shelly-blu.js](https://github.com/ALLTERCO/shelly-script-examples/blob/main/ble-shelly-blu.js) [ble-events-handler.js](https://github.com/ALLTERCO/shelly-script-examples/blob/main/ble-events-handler.js)

**Comment by taulfsime** [comment]
Thank you for the report.

Shelly PlugSG3 has matter which limits the resources for the scripts, that's why you are running out of memory. 

With 1.5 release, we will add option to disable the matter if you don't use it and the script should work fine

**Comment by taulfsime** [comment]
Nothing can be done from the script side, so im closing the issue.

**Comment by alexwala** [comment]
👍
