### ISSUE TITLE
Add date to GetStatus or add function to get date out of unix timestamp

### ISSUE THREAD

**Issue by runsnbunsn** [ALLTERCO/shelly-script-examples#15]
Maybe I am missing something here, but when playing around with Shelly scripting on my Shelly Plus 1PM I cannot find a function to convert the unix timestamp from `Sys.getStatus` to a date in the `YYYYMMDD` format.
We have the `time` already, I think we should have a `date` too. Or alternatively the [Date class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) from Javascript.
Need this to send Solar data to the [PVOutput API](https://pvoutput.org/help/api_specification.html).

**Comment by runsnbunsn** [comment]
Thx, was thinking about that too but never came to it

**Comment by wimleers** [comment]
It's rather silly that Shelly/mJS doesn't support `Date()`, but definitely _absurd_ that there's zero support for timestamp-to-date-and-time in the provided API/library 🤯 

I ported http://howardhinnant.github.io/date_algorithms.html to JavaScript to make it happen.

For example, to send power & energy consumption data to https://pvoutput.org, one MUST provide YYYYMMDD and HH:MM:SS data.

Shelly, please add this so we all can stop reinventing the wheel 🙏 😊

**Comment by Mircho** [comment]
Actually...
We'll have JS Data, but in 1.0.1. We are stabilizing the release of 1.0 but Date is already in master.

**Comment by wimleers** [comment]
Excellent news! 😊

**Comment by pjmm1** [comment]
It would be good to know when this will be released.

**Comment by taulfsime** [comment]
:) 

https://shelly-api-docs.shelly.cloud/gen2/changelog

**Comment by wimleers** [comment]
When will a stable release happen (it's in `1.0.0-beta5`)?

Or are these `1.0.0-betaX` releases more reliable than the `0.14.X` releases I've been on so far?

**Comment by runsnbunsn** [comment]
Works fine for me with beta5
example for`YYYYMMDD` format:
```
function getCurrentDate() {
  let today = new Date;
  let month = today.getMonth() + 1;
  let day = today.getDate();
  if(month < 10) {
   month = "0" + month;
  }
  if(day < 10) {
   day = "0" + day;
  }
  return today.getFullYear() + month + day;
}

**Comment by runsnbunsn** [comment]
closing issue because the problem has been solved
