### ISSUE TITLE
broken SHELLY_MJS.md? 

### ISSUE THREAD

**Issue by 0xbeefbeef** [ALLTERCO/shelly-script-examples#25]
On my Shelly 1 PM Plus Web frontend, I get an error when navigating to *Scripts->Library*:

Firmware versions teste:  0.12 and 0.13

URL used in the library dialog is the default one:
https://raw.githubusercontent.com/ALLTERCO/shelly-script-examples/main/SHELLY_MJS.md

Error message I get:
 _TypeError: r.split(...)[1] is undefined
Couldn't load library. Please try again or reset the library to default._

Seems to be related to yesterdays commit, as it was working before.

**Comment by eurich** [comment]
this is a pull request which needs to be approved and merged by an Allterco employee.
