### ISSUE TITLE
Script request: HTTPServer

### ISSUE THREAD

**Issue by lauramielke** [ALLTERCO/shelly-script-examples#29]
I am struggling with how to use the HTTPServer and would love to see your take on it. Could you maybe add a script using the HTTPServer? So far it seems the only feature not represented in this extensive and helpful script collection. 

 Anyway, thanks for the awesome work so far, its a lot of fun to check it out!

**Comment by Bascht74** [comment]
@eurich Is there a way to call http://<ip>/script/<id>/testserver?turn=on with username & password if you set a password for the shelly?

http://<ip>/script/<id>/testserver?turn=on&user=admin&username=xyz doesn't work
