### ISSUE TITLE
Script to make gen2 shelly accept GET /status like gen1

### ISSUE THREAD

**Issue by bostjanlaba** [ALLTERCO/shelly-script-examples#44]
I have a controller which calls gen1 shelly with rest api GET /status. gen2 does not have /status but I cannot change controller.

Is there a script for gen2 (Pro 3EM) which would make gen2 respond to /status call?

Thank you

**Comment by taulfsime** [comment]
@bostjanlaba No, get2 devices response only to an rpc calls. 
You will need to call /rpc/Shelly.GetStatus

**Comment by bostjanlaba** [comment]
> @bostjanlaba No, gen2 devices response only to an rpc calls. You will need to call /rpc/Shelly.GetStatus

Thank you for super fast response.
