### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by wimleers** [ALLTERCO/shelly-script-examples#54]
Per https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Mqtt/#step-3-set-a-new-mqtt-configuration, it's possible to configure one's Shelly to use `host:port`, with `host` a DNS-resolved hostname:
```
broker.hivemq.com:1883
```

This suggests that `foo.local:1883` should also work. But it does not. It appears only the default DNS server in the LAN is used (for my ISP `telenet.be` that's `195.130.130.2`) — quoting the websocket debug log:
```
{"ts":1689279084.923, "level":2, "data":"mgos_mqtt_conn.c:442    MQTT0 connecting to mist.local:1883\n}
{"ts":1689279084.948, "level":0, "data":"mongoose.c:12127        Failed to resolve 'mist.local', server 195.130.130.2\n"}
{"ts":1689279084.953, "level":2, "data":"mgos_mqtt_conn.c:189    MQTT0 TCP connected error (-1)\n"}
{"ts":1689279084.958, "level":2, "data":"mgos_mqtt_conn.c:221    MQTT0 disconnected\n"}
{"ts":1689279084.963, "level":2, "data":"mgos_mqtt_conn.c:527    MQTT0 connecting after 65028 ms\n"}
```

Surely [mDNS support](https://en.wikipedia.org/wiki/Multicast_DNS) makes a ton of sense in the typical LAN context where Shelly devices are used? 😊 🙏 🤞

**Comment by rihardsgrislis** [comment]
I agree, was bummed out it doesn't work when setting MQTT server (I've it running on my Raspberry Pi) or use mDNS names in scripting. 

I especially like mDNS because I can't reliably set static IPs for my IoT devices. Makes life so much easier! 💯

**Comment by Mircho** [comment]
I don't know exactly what kind of scripts you are trying to run but just tested:

```
avahi-browse --all
+  wlan0 IPv6 shellyplus1pm-3c6105726bd0                    _shelly._tcp         local
...
+  wlan0 IPv6 shellyplus1pm-3c6105726bd0                    Web Site             local
```

And using this script:

```
function httpCallMDNSName(name) {
  let _url = 'http://'+name+'/rpc/switch.set?id=0&on=true';
  console.log('Calling ', _url);
  Shelly.call('HTTP.GET', {
    url:_url
  }, function(result, err_code, err_message) {
    if(err_code === 200) {
      console.log('I turned on the lamp!');
    }
  })
}

let shellyMDNSName = 'shellyplus1pm-3c6105726bd0';

httpCallMDNSName(shellyMDNSName);
```

resulted in:
```
shelly_user_script.:370 Running 'script_3.js'...
14:58:55
Calling http://shellyplus1pm-3c6105726bd0/rpc/switch.set?id=0&on=true
14:58:55
shelly_ejs_rpc.cpp:41 Shelly.call HTTP.GET {"url":"http://shellyplus1pm-3c6105726bd0/rpc/switch.set?id=0&on=true"}
14:58:55
shelly_user_script.:341 JS RAM stat: after user code: 104568 after: 101492, used: 3076
14:58:55
shelly_notification:163 Status change of script:3: {"id":3,"running":true}
14:58:55
shos_rpc_inst.c:230 HTTP.GET via loopback
14:58:55
shelly_http_client.:308 0x3ffe6700: HTTP GET http://shellyplus1pm-3c6105726bd0/rpc/switch.set?id=0&on=true
14:58:55
shelly_http_client.:608 0x3ffe6700: Finished; bytes 132, code 200, redir 0/3, auth 0, status OK
14:58:55
```

The Shelly running the script was with 1.0 beta 6 firmware. You can use the `.local` domain or omit it

**Comment by rihardsgrislis** [comment]
@Mircho I'm running Firmware: 0.14.1 and I have this sample for testing (ShellyPro2PM-EC62608C9A28.local is the device itself but calling my raspberry didn't work either):
```
function processHttpResponse(result, error_code, error) {
  if (error_code !== 0) {
      console.log("error:" +error);
      console.log(error_code);
    } else {
      console.log(result.body);
    }
}

Shelly.call("HTTP.GET", {url: "http://ShellyPro2PM-EC62608C9A28.local"}, processHttpResponse);
```

Output: 
```
error:Resource unavailable: HTTP connect error -1!
-114
```

**Comment by rihardsgrislis** [comment]
Oh and @wimleers! After updating to firmware `1.0.0-beta6` setting mDNS domain for MQTT server also works, got connected. 👏🏼

**Comment by Mircho** [comment]
As we move forward and 1.0 will address these troubles I consider this good for closing. Thanks for reporting and chasing this together with us.

**Comment by wimleers** [comment]
Works perfectly in `1.0.5` and `1.0.6-beta` 👍
