### ISSUE TITLE
call HTTPServer (script) with web password on from a shelly Gen1

### ISSUE THREAD

**Issue by Bascht74** [ALLTERCO/shelly-script-examples#55]
Hi, I set a web password for my shelly plus 2pm

With that web password set, I cannot call the script (that I created) from another shelly. 

Is there any way to pass the password via the URL like the Gen1 do?
... or to disable the password protection for my script (but not for the shelly)?

with the old shelly you could add `&user=admin&password=xyz` to the url and you are done...

Thx for any hints,

Sebastian

**Comment by taulfsime** [comment]
@Bascht74 you can pass the credentials with the request just by adding username:password pair before the ip, then @ and the ip. Example - http://admin:passord@192.168.33.1/rpc/...

Make sure the app sends the request supports SHA256 algorithm

**Comment by taulfsime** [comment]
@Bascht74 Actually, this is possible only with Gen2 (Plus or Pro) device running at least 1.0-beta version. Its not possible to send requests to password-protected Gen2 devices from Gen1 devices.
