### ISSUE TITLE
Shelly WiFi Button gateway example

### ISSUE THREAD

**Issue by BrianLeishman** [ALLTERCO/shelly-script-examples#57]
I have a Shelly Plus Plug US and a Shelly WiFi Button, and the ble Shelly button gateway example looks like almost exactly what I want but for a bluetooth button.

Essentially my goal is for my WiFi button to hit an endpoint that's https but I see that thw WiFi button [doesn't really support](https://www.reddit.com/r/ShellyUSA/comments/10ab7pa/cant_get_shelly_button1_to_hit_external_url/) encrypted web traffic. 

So Using the plug as a gateway sounds like the next best thing, but the ble example is quite specifically ble and I don't know how I'd do the same for a WiFi button.

**Comment by taulfsime** [comment]
@BrianLeishman you can't use the script for the Wi-Fi button, but you can create a custom end point on the plug that the button can hit and trigger the automation
