### ISSUE TITLE
ble-pasv-mqtt-gw.js - Add other measures of XIAOMI MIFLORA

### ISSUE THREAD

**Issue by chris777c** [ALLTERCO/shelly-script-examples#89]
**Is your feature request related to a problem? Please describe.**

I use ble-pasv-mqtt-gw.js for Xiaomi device like Xiaomi Lywsd03 and I was surprise me when  show me up other equipment . The script show me a temperature of my [Xiaomi MIFLora](https://www.techpunt.nl/fr/xiaomi-mi-flower-care-plant-sensor.html)  with this payload on path : 

`shellies/blegateway/c99c9d9999ca/temperature`
with json
`{"temperature":18.4,"rssi":-78}` 

**Describe the solution you'd like**
How can help you to integrate other attributes of this device, like : 
- battery
- moisture
- sunlight
- fertility
- firmware

**Comment by pytekmobile** [comment]
I've created a pull request for Xiaomi Mi Flora devices. It contains illumination, moisture and soil. Battery isn't possible because with a firmware update Xiaomi stopped sending the battery level. Firmware isn't sent too.

**Comment by Mircho** [comment]
Closed with #92
