### ISSUE TITLE
ble-events-handler.js - change mac to adress?

### ISSUE THREAD

**Issue by beckma** [ALLTERCO/shelly-script-examples#90]
I think, there's a bug in ble-events-handler.js

Is it possible that "mac" needs to be changed to "address" here?

![image](https://github.com/ALLTERCO/shelly-script-examples/assets/6991499/f9996908-139b-4826-b281-35322e295d76)

**Comment by taulfsime** [comment]
Yes, right. Thanks for the report. 

Updated with https://github.com/ALLTERCO/shelly-script-examples/pull/96
