### ISSUE TITLE
ble-shelly-dw.js does not do anything

### ISSUE THREAD

**Issue by DaveMe81** [ALLTERCO/shelly-script-examples#91]
Hello!

I've got an issue with the script of: ble-shelly-dw.js

I got a Shelly BLU DoorWindow. As you can see in the screenshot, I copied the address inserted and run the script. Nothing happens. Where is my error?

![image](https://github.com/ALLTERCO/shelly-script-examples/assets/49861775/3d658762-b889-446f-9f2d-880bf7d9115b)

Thank you for your help!

**Comment by DaveMe81** [comment]
Now I disabled the gateway option in the Bluetooth settings. Now I get rif of the "scanner already taken" issue. But still no reation.

![image](https://github.com/ALLTERCO/shelly-script-examples/assets/49861775/46bb7834-346e-49df-9ba6-caa0e3ce02e5)

**Comment by taulfsime** [comment]
Hello, @DaveMe81 
Yeah the Bluetooth scan is shared across the device between observer, scripts and etc. 

For the script "to do" something you have to populate both window open/close functions.

**Comment by DaveMe81** [comment]
I installed FW 1.2.2 now, and it working now. So, deactive the bluetooth gateway in the settings, starting the script and voila works.
