### ISSUE TITLE
ble-shelly-blu missing data types for humidity and temperature for the new BLU H&T device

### ISSUE THREAD

**Issue by dirgoDK** [ALLTERCO/shelly-script-examples#94]
The temperature and humidity values are reported as 0x45 and 0X2E so the payload fails and the emit data is missing the humidity and the temperature values

the BTH const must be extended to look like:
const BTH = {
  0x00: { n: "pid", t: uint8 },
  0x01: { n: "battery", t: uint8, u: "%" },
  0x02: { n: "temperature", t: int16, f: 0.01, u: "tC" },
  **0x45: { n: "temperature", t: int16, f: 0.1, u: "tC" },**
  0x03: { n: "humidity", t: uint16, f: 0.01, u: "%" },
  **0x2E: { n: "humidity", t: uint8, f: 1, u: "%" },**
  0x05: { n: "illuminance", t: uint24, f: 0.01 },
  0x21: { n: "motion", t: uint8 },
  0x2d: { n: "window", t: uint8 },
  0x3a: { n: "button", t: uint8 },
  0x3f: { n: "rotation", t: int16, f: 0.1 },
};

**Comment by taulfsime** [comment]
Thanks for the report, both object ids are added with https://github.com/ALLTERCO/shelly-script-examples/pull/95
